# Generated by Django 5.1.1 on 2024-09-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(default='Sadeed'),
        ),
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank='True', default='', upload_to=''),
        ),
    ]
