# Generated by Django 5.1.1 on 2024-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_author_blog_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Sadeed', max_length=40),
        ),
    ]
