# Generated by Django 5.1.1 on 2024-09-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('location', models.TextField()),
                ('company', models.TextField()),
                ('salaryrange', models.TextField()),
                ('jobtype', models.TextField()),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('applylink', models.URLField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('expirydate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
