# Generated by Django 5.1.1 on 2024-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_company_alter_job_jobtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
